name: build

on:
    push:
        branches: [main]
        paths-ignore:
            - Makefile
            - README.md
    pull_request:
        branches: [main]
        paths-ignore:
            - Makefile
            - README.md
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: "stable"

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libsqlite3-dev
                  go get .

            - name: Test and build
              run: make test build

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: redka
                  path: build/redka
                  retention-days: 7
